$(function(){
	$(".nav-li").hover(function(){
		$(this).find('span').css('display','none')
		$(this).find('.nav-down-list').css('display','block')
	},function(){
		$(this).find('span').css('display','block')
		$(this).find('.nav-down-list').css('display','none')
	})
	     $(window).scroll(function(){
        	if($('html,body').scrollTop()>200){
        		$('.back-top').css('display','block')
        	}
        	else{
        		$('.back-top').css('display','none')
        	}
        })
        $('.back-top').click(function(){
        	$('html,body').scrollTop(0)
        })
        $('.back-top').hover(function(){
        	$(this).addClass('now')
        },function(){
        	$(this).removeClass('now')
        })
        $(".down-search").hover(function(){
        	$(this).addClass('now')
        },function(){
        		$(this).removeClass('now')
        })
        $('.search-btn').click(function(){
        	$(this).toggleClass('now')
        	if($(this).hasClass('now')){
        	$(".down-search").addClass('now')	
        	}
        	else{
        	$(".down-search").removeClass('now')	
        	}
        })
	})